include: package:lints/recommended.yaml

linter:
  rules:
    - cascade_invocations
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - unnecessary_new