name: easy_copy_with
description: Code generator for automatic copyWith methods in Dart classes using @CopyWith annotation.
version: 5.0.0
homepage: https://github.com/inoek/easy_copy_with
repository: https://github.com/inoek/easy_copy_with
issue_tracker: https://github.com/inoek/easy_copy_with/issues

environment:
  sdk: ^3.11.0

dependencies:
  easy_copy_with_annotation: ^1.0.0
  build: ^4.0.6
  source_gen: ^4.2.3
  analyzer: ^13.0.0

dev_dependencies:
  test: ^1.31.1
  build_runner: ^2.15.0
  lints: ^6.0.0
  build_test: ^3.5.15
  source_gen_test: ^1.3.6
  equatable: ^2.0.8

topics:
  - codegen
  - copy-with
  - code-generation
  - source-gen
